### ISSUE TITLE
"Found dependencies whose dependents changed" but ./gradlew --write-locks doesn't fix it

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-consistent-versions#117]
## What happened?

@mglazer reported in `#dev-foundry-infra` that CI for his project was failing with:

```
Found dependencies whose dependents changed: {org.eclipse.jgit:org.eclipse.jgit=(Line{group=org.eclipse.jgit, name=org.eclipse.jgit, version=5.3.1.201904271842-r, numDependents=1, dependentsHash=40088599}, Line{group=org.eclipse.jgit, name=org.eclipse.jgit, version=5.3.1.201904271842-r, numDependents=1, dependentsHash=dc0be413})}. Please run './gradlew --write-locks'.
```

But running `./gradlew --write-locks` didn't make any changes.

## What did you want to happen?

This kind of error message should never happen! Maybe there should be a clearer 'verify lock file' command instead of re-purposing the `resolveConfigurations` command?

**Comment by dansanduleac** [comment]
Fixed by #119
