### ISSUE TITLE
Tracking: lock test dependencies 

### ISSUE THREAD

**Issue by dansanduleac** [palantir/gradle-consistent-versions#131]
## What happened?

Currently, we only only track production dependencies in `versions.lock`.
This is great for looking up at a glance what dependencies will be used in production, but it might hide the fact that tests are passing because one of the production dependencies' version got bumped transitively through some other testing utilities library.

## What did you want to happen?

Lock test dependencies too, but in a way that's clearly separated from the production dependencies.
As in, it should be obvious looking at the lock file which dependencies are used in production, and which are only used in tests.

Checklist:

- [ ] investigate how to track dependency provenance (e.g. it only came from `testCompileClasspath`)
- [ ] devise lock file structure changes to accommodate a separation of dependencies used in production / test / maybe other source sets

**Comment by iamdanfox** [comment]
Implemented in 1.9.0
