### ISSUE TITLE
Warn if versions.props has lower value than used in versions.lock

### ISSUE THREAD

**Issue by ogaragatyi** [palantir/gradle-consistent-versions#310]
## What happened?
When versions.props suggests some dependency X version 1.0.0 but some dependency Y requests version 1.1.0 version.locks contains latter version. This makes entry of versions.props X = 1.0.0 useless.

## What did you want to happen?
Have a warning on build that entry X = 1.0.0 in versions.props can be updated to value 1.1.0 as it is already used in versions.lock. 
I think it might be more useful to have such a warning only for direct dependencies of a project, and not warn about transitive ones. The reason is that transitive dependencies might change more often than direct dependencies because of direct dependencies version changes.

**Comment by iamdanfox** [comment]
This is coming from a mostly aesthetic perspective right? Did something undesirable actually happen?

**Comment by ogaragatyi** [comment]
We would like to have a consistent versions in the versions.props. There is no value in having there versions that don't correlate with what is actually in class path

**Comment by iamdanfox** [comment]
I'd encourage you to read through the motivation in the README, we call out that versions.props is a [lower bound for dependencies](https://github.com/palantir/gradle-consistent-versions#concepts) as the very first important concept.

This is actually a really fundamental design decision of GCV. We used to rely on nebula dependency recommender, which had the behaviour you describe (X=1.0.0 in versions.props was _forced_ everywhere) but this was actively dangerous and caused plenty of P0s, including NoSuchMethodErrors etc at runtime.

This is also why we added the versions.lock file, so you can consider versions.props 'inputs' to the system and versions.lock is like an 'output'.

**Comment by ogaragatyi** [comment]
I read the docs, not a single time. I understand that and do not say that it needs to be enforced, but without any identification that there is a discrepancy versions.props is not that meaningful.
Surely, I can check it in lock file, but warning would make it clearer and rely less on people's attention. But anyway, if you see it is going against you tastes in the project I can do much to change your mind
