### ISSUE TITLE
dependencyInsight broken on 1.12.4

### ISSUE THREAD

**Issue by jdm2212** [palantir/gradle-consistent-versions#314]
After upgrading from 1.11.2 to 1.12.4, dependencyInsight does not work on a project that uses `compile project(":other-project")`.

The gradle build scan shows dependencyInsight trying and failing to resolve `com.myproject:other-project:version` on maven rather than just using the Gradle project that's right there.

I can share the build scan and exact project internally.

**Comment by dansanduleac** [comment]
Can't remember the context of this but I suspect it's possibly to do with the antlr plugin, if you're using that.

Also, please make sure never to run `dependencyInsight` with `--configuration compile` but instead always with `--configuration compileClasspath` (the default).

**Comment by dansanduleac** [comment]
It's been a while so closing this but please reach out internally if this is still happening.
