### ISSUE TITLE
Plugin to throw except if merge conflicts get into the version.props

### ISSUE THREAD

**Issue by qinfchen** [palantir/gradle-consistent-versions#353]
## What happened?
We accidentally merged a merge conflict to version.props and were surprised to find out that the plugin accepts the bad format, which is kind of undefined.

```
#test
<<<<<<< HEAD
com.test.me:* = 3.4.5
com.test.friend:* = 10.31.1
=======
com.test.me:* = 3.4.6
com.test.friend:* = 10.20.
>>>>>>> Upgrade dependencies
```

## What did you want to happen?
Throws an error indicating that the versions specified in the versions.props are invalid.

**Comment by dansanduleac** [comment]
Think this is now addressed by much stricter parsing in #375.
