### ISSUE TITLE
Downgrading starred dependencies (virtual platform)?

### ISSUE THREAD

**Issue by dweiss** [palantir/gradle-consistent-versions#356]
Hmm... sorry for being dim but when you declare a starred dependency like so:
```
org.slf4j:*=1.7.24 
```
how do you downgrade it if one of the other dependencies upgrades the whole set to 1.7.25? I'd like to keep it at 1.7.24... This doesn't work:
```
allprojects {
  configurations.all {
    resolutionStrategy {
      force 'org.slf4j:slf4j-api:1.7.24'
    }
  }
}
```
claiming:
```
> Could not resolve all dependencies for configuration ':foo:bar:detachedConfiguration1Copy'.
   > Could not resolve org.slf4j:slf4j-api:{strictly 1.7.24}.
     Required by:
         project :solr:core
      > Cannot find a version of 'org.slf4j:slf4j-api' that satisfies the version constraints:
           Dependency path '....' --> 'org.apache.kerby:kerby-pkix:1.0.1' --> 'org.slf4j:slf4j-api:1.7.25' because of the following reason: belongs to platform org.slf4j:_:1.7.25
...
```

Any hints?

**Comment by dweiss** [comment]
This works, but don't know if it's the right way to solve it.
```
subprojects {
  plugins.withType(JavaPlugin) {
    dependencies {
      implementation enforcedPlatform('org.slf4j:slf4j-api:1.7.24')
    }
  }
}
```

**Comment by dansanduleac** [comment]
Hey @dweiss, sorry took so long to get back to you!

In general we advise people to not try to forcefully downgrade dependencies, and instead try to exclude transitive dependency edges that they think are incorrect / too strict. (can add more info on this but I don't think this is your particular problem, so just mentioning it as a note)

I think what you're getting hit by here is that detached configurations are ad-hoc and not added to the project's `configurations` container, thus your `configurations.all` code will not configure it.

If your detached configuration extends the `implementation` configuration though (whether directly or transitively), then it would make sense that it picks up the `enforcedPlatform` that way.

**Comment by dweiss** [comment]
bq. In general we advise people to not try to forcefully downgrade dependencies,

In general I hope life would be simpler too. :) 

bq. think what you're getting hit by here is that detached configurations are ad-hoc and not added to the project's configurations container, thus your configurations.all code will not configure it.

Yes, this could be the case. Thanks for the hint.
