### ISSUE TITLE
checkUnusedConstraints reports unused pin while it's being used (and required)

### ISSUE THREAD

**Issue by dweiss** [palantir/gradle-consistent-versions#383]
So this one seems legit (no typos this time):
```
git clone https://github.com/apache/lucene-solr -b gradle-master --depth 1
cd lucene-solr
git checkout ae2e4f3ae9bb
./gradlew checkUnusedConstraints
```
fails with:
```
> There are unused pins in your versions.props:
  [org.apache.rat:apache-rat:0.11]
```
but this dependency is being used in root project's detached configuration to set up validation tasks:

https://github.com/apache/lucene-solr/blob/gradle-master/gradle/validation/rat-sources.gradle#L22-L30

When you remove the pinned version and re-run:
```
./gradlew rat --rerun-tasks
```
it'll bail out with an error:
```
* What went wrong:
Execution failed for task ':solr:rat'.
> Could not resolve all files for configuration ':ratDeps'.
   > Could not find org.apache.rat:apache-rat:.
     Required by:
         project :
```

**Comment by dweiss** [comment]
@dansanduleac Would you mind taking a look if it's a bug or misuse of the plugin somehow?

**Comment by dweiss** [comment]
To be more specific: is using the plugin to resolve script (and other non-compilation) dependencies something supported? I see the lock file doesn't have this dependency when regenerated either (although clearly it's being resolved correctly when you run the task).

**Comment by ferozco** [comment]
Hey @dweiss looks like this is actually another typo since GCV expects each line of versions.props to look like `<group>:<name> = <version>`. We added better validation in 1.15.0 (https://github.com/palantir/gradle-consistent-versions/pull/375) so that you should get a more explicit error if you upgrade.

**Comment by dweiss** [comment]
Rats. Indeed, it might have been a type. Interesting that it worked (resolved properly)... I'll check when I get back to it. Thank you.
