### ISSUE TITLE
Update Gradle Constraints link

### ISSUE THREAD

**Issue by tpittmanVS** [palantir/gradle-consistent-versions#644]
Hyperlink to "Gradle constraints" in readme.MD is broken (https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:dependency_constraints).  

Also, a clarifying question (sorry if this is the wrong forum): is this consistent versions or versions.prop framework completely defined by the palantir plugin only or is it also leveraging some other plugins or Gradle concepts, eg for the lock file?

**Comment by iamdanfox** [comment]
The lockfile and versions.props are palantir-made up concepts (we wrote a little section about why we designed this format to prefer _textual_ merge conflicts over semantic merge conflicts): https://github.com/palantir/gradle-consistent-versions#are-these-vanilla-gradle-lockfiles

But under the hood, this plugin just uses first-class gradle features, e.g. [virtual platforms](https://docs.gradle.org/current/userguide/dependency_version_alignment.html), and 'strictly constraints'.
