### ISSUE TITLE
Artifact not being included in the platform despite '*' constraint in versions.props

### ISSUE THREAD

**Issue by robert3005** [palantir/gradle-consistent-versions#68]
## What happened?
I was unable to make a small repro for this but have internal repo that exhibits this behaviour. If you have a start constraint on a dependency it might not include all artifacts in the virtual platform which then if that dependency comes from transitive results in wrong versions.lock and unsatisfiable constraints upon resolution

## What did you want to happen?

conflict resolution should pick higher version and update lock file

ping @dansanduleac or me if you want the link to the internal repro

**Comment by dansanduleac** [comment]
This has probably been fixed by various Gradle dependency resolution improvements since then, so I think we can close this.
