### ISSUE TITLE
Gradle 7 compatibility

### ISSUE THREAD

**Issue by dweiss** [palantir/gradle-consistent-versions#700]
Is there any time frame to support gradle 7? I've tried to upgrade but looks like things break on removed legacy configurations.

https://github.com/palantir/gradle-consistent-versions/blob/ccb79b612128591efb2a829f0cb6fe6bc76585c0/src/main/java/com/palantir/gradle/versions/FixLegacyJavaConfigurationsPlugin.java#L56-L68

```
* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin class 'com.palantir.gradle.versions.FixLegacyJavaConfigurationsPlugin'.
   > Configuration with name 'compile' not found.
```

**Comment by fawind** [comment]
Sorry for the delay here! We just started working on Gradle 7 compatibility but the latest release (2.0.0) should be compatible now. Let us know if you run into further issues!

**Comment by dweiss** [comment]
Thank you! I'll be looking into upgrading various projects soon, this will be very useful!
